- alias: "Set Initial Laundry Time on Cycle Change"
  description: "Update static initial laundry time when the cycle changes."
  trigger:
    - platform: state
      entity_id: sensor.##REPLACE##_laundry_cycle  # Replace with the actual entity ID for the cycle state
  condition:
    - condition: template
      value_template: "{{ states('sensor.##REPLACE##_laundry_time_remaining') not in ['unknown', 'unavailable'] }}"
  action:
    - service: homeassistant.update_entity
      target:
        entity_id: sensor.static_initial_laundry_time
